**ndarray 생성 실습**

**Numpy ndarray 개요**

ndarray 생성 `np.array()`

In [6]:
import numpy as np

list1 = [1,2,3]
print('list', list1)
print('list1 type', type(list1))

array1 = np.array(list1)
print('array1', array1)
print('array1 type', type(array1))

list [1, 2, 3]
list1 type <class 'list'>
array1 [1 2 3]
array1 type <class 'numpy.ndarray'>


ndarray의 형태(shape)와 차원

In [7]:
array1 = np.array([1,2,3])
print('array1 type', type(array1))
print('array1 array 형태', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type', type(array2))
print('array2 array 형태', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type', type(array3))
print('array3 array 형태', array3.shape)

array1 type <class 'numpy.ndarray'>
array1 array 형태 (3,)
array2 type <class 'numpy.ndarray'>
array2 array 형태 (2, 3)
array3 type <class 'numpy.ndarray'>
array3 array 형태 (1, 3)


In [9]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [10]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [14]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [15]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


**ndarray에서 axis기반의 연산함수 수행**

In [16]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
print(array2.sum())
print(array2.sum(axis = 0))
print(array2.sum(axis = 1))

15
[3 5 7]
[6 9]


**ndarray를 편리하게 생성하기**- `arange`,`zeros`,`ones`

In [17]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [18]:
zero_array = np.zeros((3,2),dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [20]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**ndarray의 shape를 변경하는** `reshape()`

In [22]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


`reshape()`**에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray형태 반환**

In [23]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
print('array2:\n', array2)

array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)
print('array3:\n', array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [25]:
array1.reshape(-1,-1)

ValueError: can only specify one unknown dimension

**ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)**

특정 위치의 단일값 추출

In [28]:
array1 = np.arange(start = 1, stop = 10)
print('array1 :', array1)

value = array1[2]
print('value :', value)
print(type(value))

array1 : [1 2 3 4 5 6 7 8 9]
value : 3
<class 'numpy.int32'>


In [30]:
print('last value :', array1[-1], 'second last value :', array1[-2])

last value : 9 second last value : 8


**슬라이싱(slicing)**

In [31]:
array1 = np.arange(start = 1, stop = 10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


**배열의 정렬**

`sort()`
- `np.sort()` : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- `ndarray.sort()` : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

`np.sort()`나 `ndarray.sort()` 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬

내림차순으로 정렬하기 위해서는 [::-1] 적용 ex. np.sort()[::-1]