# 데이터 인코딩

**레이블 인코딩(Label encoding)**

In [8]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자렌지', '컴퓨터' ,'선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 :', labels)

인코딩 변환값 : [0 1 4 5 3 3 2 2]


In [10]:
print('인코딩 클래스 :', encoder.classes_)
print('\n디코딩 원본값 :', encoder.inverse_transform([2,5,1,3,0,4]))

인코딩 클래스 : ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']

디코딩 원본값 : ['믹서' '컴퓨터' '냉장고' '선풍기' 'TV' '전자렌지']


**원-핫 인코딩(One-Hot encoding)**

In [12]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고' ,'전자렌지', '컴퓨터' ,'선풍기' ,'선풍기', '믹서', '믹서']

encoder = LabelEncoder()
labels = encoder.fit_transform(items)

labels = labels.reshape(-1,1)

oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)

print('원-핫 인코딩 데이터\n',oh_labels.toarray())
print('원-핫 인코딩 데이터 차원\n', oh_labels.shape)

원-핫 인코딩 데이터
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
 (8, 6)


# 피처 스케일링과 정규화
**StandardScaler**

In [13]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)

print('feature들의 평균값\n', iris_df.mean())
print('\nfeature들의 분산 값\n', iris_df.var())


feature들의 평균값
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
iris_scaled = scaler.fit_transform(iris_df)

# transform()시 scale 변환된 데이터 셋이 numpy ndarray로 반환되어 이를 DataFrame으로 반환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print('feature들의 평균값\n', iris_df_scaled.mean())
print('\nfeature들의 분산\n', iris_df_scaled.var())

feature들의 평균값
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64
